# Generated by Django 5.1.6 on 2025-03-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
